I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 34, in script
    "40% Chance of Correct Identification of Mission."
ValueError: unsupported format character 'C' (0x43) at index 4

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 34, in script
    "40% Chance of Correct Identification of Mission."
  File "C:\Users\msree\Downloads\renpy-8.3.7-sdk\renpy\ast.py", line 2586, in execute
    Say.execute(self)
  File "C:\Users\msree\Downloads\renpy-8.3.7-sdk\renpy\ast.py", line 623, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "C:\Users\msree\Downloads\renpy-8.3.7-sdk\renpy\exports\sayexports.py", line 121, in say
    what = what % tag_quoting_dict
ValueError: unsupported format character 'C' (0x43) at index 4

Windows-10-10.0.26100 AMD64
Ren'Py 8.3.7.25031702
Fate Conduction 1.0
Sat Oct 11 21:11:36 2025
